{{- if .Values.config.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-cpi
  labels:
    app: {{ template "cpi.name" . }}
    vsphere-cpi-infra: secret
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: cloud-controller-manager
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{ .Values.config.vcenter }}.username: {{ .Values.config.username }}
  {{ .Values.config.vcenter }}.password: {{ .Values.config.password }}
{{- end -}}
